name: Generate and push new key

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every hour

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run key generator script
        run: node generate-key.js

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Add new encrypted key [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
